/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu;

import java.awt.Dimension;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.Icon;

/**
 *
 * @author Asus
 */
public class MenuItem extends javax.swing.JPanel {

    /**
     * @return the showing
     */
   

    /**
     * @param showing the showing to set
     */
    public void setShowing(boolean showing) {
        this.showing = showing;
    }

    /**
     * @return the subMenu
     */
    public ArrayList<MenuItem> getSubMenu() {
        return subMenu;
    }

    /**
     * Creates new form MenuItem
     */
    private final ArrayList<MenuItem> subMenu =new ArrayList<>();
    private ActionListener act;
    
    public MenuItem(Icon icon, String menuName,ActionListener act, MenuItem... subMenu) {
        initComponents();
        lblicon.setIcon(icon);
        lblname.setText(menuName);
        
        //action
        if(act!=null){
            this.act = act;
        }
        
        this.setSize(new Dimension(Integer.MAX_VALUE,45));
        this.setMaximumSize(new Dimension(Integer.MAX_VALUE,45));
        this.setMinimumSize(new Dimension(Integer.MAX_VALUE,45));
        
     for (int i=0;i<subMenu.length;i++){
         this.subMenu.add(subMenu[i]);
         subMenu[i].setVisible(false);
     }
        
    
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        lblicon = new javax.swing.JLabel();
        lblname = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        lblname.setText("MENU NAME HEREE....");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblicon, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblname, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblicon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblname, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents
private boolean showing=false;
    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
    if(showing){
        hideMenu();
    }else{
        showMenu();
    }
    if(act!=null){
        act.actionPerformed(null);
    }
    }//GEN-LAST:event_formMousePressed

private void showMenu(){
new Thread(new Runnable() {
    @Override
    public void run() {
        for(int i=0; i<subMenu.size();i++){
            sleep();
            subMenu.get(i).setVisible(true);
        }
          showing=true;
          getParent().repaint();
          getParent().revalidate();
    }
}).start();
}

private void hideMenu(){
    new Thread(new Runnable() {
    @Override
    public void run() {
        for(int i=subMenu.size()-1;i>=0;i--){
            sleep();
            subMenu.get(i).setVisible(false);
            subMenu.get(i).hideMenu();
        }
          showing=false;
          getParent().repaint();
          getParent().revalidate();
    }
}).start();
}

private void sleep(){
    try{
        Thread.sleep(20);   
    }   catch (InterruptedException e) {
            
        }
    
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblicon;
    private javax.swing.JLabel lblname;
    // End of variables declaration//GEN-END:variables
}
