/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form_main;

import java.sql.*;
import java.sql.ResultSet;
import java.sql.Statement;
import java.awt.HeadlessException;
import java.sql.Connection;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
/**
 *
 * @author Asus
 */
public class form_anggota extends javax.swing.JPanel {

    /**
     * Creates new form form_anggota
     */
    public form_anggota() {
       
        initComponents();
        tampil_anggota();
        kosongkan_form();
        otomatis();
        
        btnsimpan2.setEnabled(true);
        btnedit2.setEnabled(false);
        btnhapus2.setEnabled(false);
        txtkode2.grabFocus();
    }
    
    public void otomatis(){
        
        try{
            Connection conn = (Connection)koneksi.configDB();
            Statement stt = conn.createStatement();
            ResultSet rs = stt.executeQuery("Select Max(Right(kode_agt,3)) as no from anggota");
            
            
            while (rs.next()) {
                if (rs.first() == false) {
                    txtkode2.setText("KA001");
                } else {
                    rs.last();
                    int auto_id = rs.getInt(1) + 1;
                    String no = String.valueOf(auto_id);
                    int NomorJual = no.length();
                    //MENGATUR jumlah 0
                    for (int j = 0; j < 3 - NomorJual; j++) {
                        no = "0" + no;
                    }
                    txtkode2.setText("KA" + no);
                }
            }
            rs.close();
            stt.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR: \n" + e.toString(),
                    "Kesalahan", JOptionPane.WARNING_MESSAGE);
        }
    }
    
    private void tampil_anggota(){
          
           DefaultTableModel model = new DefaultTableModel();
           model.addColumn("No. ");
           model.addColumn("Kode. ");
           model.addColumn("Nama. ");
           model.addColumn("Alamat. ");
           model.addColumn("No.Tlp. ");
           model.addColumn("Tanggal Lahir. ");
           model.addColumn("Status. ");
           model.addColumn("Jenis Kelamin. ");
           model.addColumn("Jabatan. ");
           model.addColumn("Divisi. ");
           model.addColumn("Agama. ");
          
           
           try{
            int no = 1;
            String sql = "SELECT * FROM anggota";
            java.sql.Connection conn = (Connection)koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            while(res.next()){
                model.addRow(new Object[]{no++,res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6),res.getString(7),res.getString(8),res.getString(9),res.getString(10)}); 
            
                tabelanggota.setModel(model);
            }
           
           }catch (SQLException e){
               System.out.println("Error :"+ e.getMessage());
           }
       } 

    private void  kosongkan_form(){
        //form anggota
        
        txtnama2.setText("");
        txtalamat2.setText("");
        txttlp.setText("");
        txttanggal2.setDate(null);
        cbstatus.setSelectedItem(this);
        cbkelamin2.setSelectedItem(this);
        cbjabatan2.setSelectedItem(this);
        cbdivisi.setSelectedItem(this);
        cbagama.setSelectedItem(this);
        txtcari2.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtnama2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtalamat2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbjabatan2 = new javax.swing.JComboBox<>();
        btnsimpan2 = new javax.swing.JButton();
        btnedit2 = new javax.swing.JButton();
        btnhapus2 = new javax.swing.JButton();
        txttanggal2 = new com.toedter.calendar.JDateChooser();
        jScrollPane9 = new javax.swing.JScrollPane();
        tabelanggota = new javax.swing.JTable();
        cbkelamin2 = new javax.swing.JComboBox<>();
        txtcari2 = new javax.swing.JTextField();
        btncari2 = new javax.swing.JButton();
        txtkode2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cbdivisi = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        cbstatus = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        cbagama = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        txttlp = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 255, 204));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel2.setText("DATA ANGGOTA");

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel3.setText("KODE ANGGOTA");

        txtnama2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnama2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel4.setText("NAMA");

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel5.setText("ALAMAT");

        txtalamat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtalamat2ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel6.setText("TANGGAL LAHIR");

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel7.setText("JENIS KELAMIN");

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel8.setText("JABATAN");

        cbjabatan2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "JENDRAL", "KOLONEL", "LETKOL", "MAYOR", "KAPTEN", "LETNAN SATU", "LETNAN DUA", "PEMBANTU LETNAN SATU", "PEMBANTU LETNAN DUA", "SERSAN KEPALA", "SERSAN SATU", "SERSAN DUA", "PRAJURIT KEPALA", "PRAJURIT SATU", "PRAJURIT DUA", "PNS " }));
        cbjabatan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbjabatan2ActionPerformed(evt);
            }
        });

        btnsimpan2.setText("SIMPAN");
        btnsimpan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpan2ActionPerformed(evt);
            }
        });

        btnedit2.setText("EDIT");
        btnedit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnedit2ActionPerformed(evt);
            }
        });

        btnhapus2.setText("HAPUS");
        btnhapus2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapus2ActionPerformed(evt);
            }
        });

        txttanggal2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txttanggal2PropertyChange(evt);
            }
        });

        tabelanggota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelanggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelanggotaMouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(tabelanggota);

        cbkelamin2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki - Laki", "Perempuan" }));
        cbkelamin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbkelamin2ActionPerformed(evt);
            }
        });

        txtcari2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcari2ActionPerformed(evt);
            }
        });

        btncari2.setText("Cari");
        btncari2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncari2ActionPerformed(evt);
            }
        });

        txtkode2.setEditable(false);
        txtkode2.setBackground(new java.awt.Color(204, 255, 204));

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel9.setText("DIVISI");

        cbdivisi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "STAFF UM", "SATLID", "SATGAL", "SATBAN", "SATSUS", "DENMA" }));
        cbdivisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbdivisiActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel10.setText("STATUS");

        cbstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Belum Menikah", "Menikah" }));
        cbstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbstatusActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel11.setText("AGAMA");

        cbagama.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ISLAM", "KATOLIK", "PROTESTAN", "BUDHA", "HINDU", " " }));
        cbagama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbagamaActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel12.setText("NO TLP");

        txttlp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttlpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnsimpan2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(btnedit2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(btnhapus2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(164, 164, 164)
                                .addComponent(txtcari2, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btncari2))
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 1049, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(157, 157, 157)
                                .addComponent(txttanggal2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel12))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtalamat2, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtnama2, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtkode2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE))
                                    .addComponent(txttlp, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel11))
                                        .addGap(80, 80, 80)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbdivisi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cbagama, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cbjabatan2, 0, 180, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel10))
                                        .addGap(38, 38, 38)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cbstatus, 0, 180, Short.MAX_VALUE)
                                            .addComponent(cbkelamin2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(65, 65, 65)))
                        .addGap(302, 302, 302))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtkode2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbkelamin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbjabatan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbdivisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbagama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnama2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtalamat2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttlp, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txttanggal2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btncari2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtcari2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnsimpan2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnedit2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnhapus2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)))
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbjabatan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbjabatan2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbjabatan2ActionPerformed

    private void btnsimpan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpan2ActionPerformed
        String tampilan ="dd-MM-yyyy";
        SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        String tanggal = String.valueOf(fm.format(txttanggal2.getDate()));

        try{
            String sql = "INSERT INTO anggota VALUES ('"+txtkode2.getText()+"','"+txtnama2.getText()+"','"+txtalamat2.getText()+"','"+txttlp.getText()+"','"+tanggal+"','"+cbstatus.getSelectedItem()+"','"+cbkelamin2.getSelectedItem()+"','"+cbjabatan2.getSelectedItem()+"','"+cbdivisi.getSelectedItem()+"','"+cbagama.getSelectedItem()+"')";
            java.sql.Connection conn = (Connection)koneksi.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Simpan Data Berhasil...");
            
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
            tampil_anggota();
            kosongkan_form();
            otomatis();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsimpan2ActionPerformed

    private void btnedit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnedit2ActionPerformed
        String tampilan ="dd-MM-yyyy";
        SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        String tanggal = String.valueOf(fm.format(txttanggal2.getDate()));

        try{
            String sql = "UPDATE anggota SET kode_agt='"+txtkode2.getText()+"',nama_agt='"+txtnama2.getText()+"',alamat_agt='"+txtalamat2.getText()+"',no_tlp='"+txttlp.getText()+"',lahir_agt='"+tanggal+"',status='"+cbstatus.getSelectedItem()+"',kelamin_agt='"+cbkelamin2.getSelectedItem()+"',jabatan_agt='"+cbjabatan2.getSelectedItem()+"',divisi='"+cbdivisi.getSelectedItem()+"',agama='"+cbagama.getSelectedItem()+"' WHERE kode_agt = '"+txtkode2.getText()+"'";
            java.sql.Connection conn = (Connection)koneksi.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Edit Data Berhasil...");
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        tampil_anggota();
        kosongkan_form();
        
        btnsimpan2.setEnabled(true);
        btnedit2.setEnabled(false);
        btnhapus2.setEnabled(false);
    }//GEN-LAST:event_btnedit2ActionPerformed

    private void btnhapus2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapus2ActionPerformed
        
        try{
            String sql = "DELETE FROM anggota WHERE kode_agt='"+txtkode2.getText()+"'";
            java.sql.Connection conn = (Connection)koneksi.configDB();
            java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Hapus Data Berhasil...");
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        tampil_anggota();
        kosongkan_form();
        
        btnsimpan2.setEnabled(true);
        btnedit2.setEnabled(false);
        btnhapus2.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnhapus2ActionPerformed

    private void txttanggal2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txttanggal2PropertyChange

    }//GEN-LAST:event_txttanggal2PropertyChange

      private java.util.Date getTanggalFromTableAnggota(JTable tabelanggota, int i) {
        JTable tabel = tabelanggota;
        String str_tgl = String.valueOf(tabel.getValueAt(tabel.getSelectedRow(), i));
        java.util.Date tanggal = null;
        try {
            tanggal = new SimpleDateFormat("dd-MM-yyyy").parse(str_tgl);
        } catch (ParseException ex) {
            Logger.getLogger(form_anggota.class.getName()).log(Level.SEVERE, null, ex);
        }
        return tanggal;
    }
    
    private void tabelanggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelanggotaMouseClicked
        int baris = tabelanggota.rowAtPoint(evt.getPoint());
        
        btnsimpan2.setEnabled(false);
        btnedit2.setEnabled(true);
        btnhapus2.setEnabled(true);
        
        String kode2 = tabelanggota.getValueAt(baris, 1).toString();
        txtkode2.setText(kode2);

        String nama2 = tabelanggota.getValueAt(baris, 2).toString();
        txtnama2.setText(nama2);

        String alamat2 = tabelanggota.getValueAt(baris, 3).toString();
        txtalamat2.setText(alamat2);
        
        String tlp = tabelanggota.getValueAt(baris, 4).toString();
        txttlp.setText(tlp);
        
        txttanggal2.setDate(getTanggalFromTableAnggota(tabelanggota,5));
        
        String status = tabelanggota.getValueAt(baris, 6).toString();
        cbstatus.setSelectedItem(status);

        String kelamin2 = tabelanggota.getValueAt(baris, 7).toString();
        cbkelamin2.setSelectedItem(kelamin2);

        String jabatan2 = tabelanggota.getValueAt(baris, 8).toString();
        cbjabatan2.setSelectedItem(jabatan2);
        
        String divisi = tabelanggota.getValueAt(baris, 9).toString();
        cbdivisi.setSelectedItem(divisi);
        
        String agama = tabelanggota.getValueAt(baris, 10).toString();
        cbagama.setSelectedItem(agama);
    }//GEN-LAST:event_tabelanggotaMouseClicked

    private void cbkelamin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbkelamin2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbkelamin2ActionPerformed

    private void txtcari2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcari2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcari2ActionPerformed

    private void btncari2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncari2ActionPerformed
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("No. ");
        model.addColumn("Kode. ");
        model.addColumn("Nama. ");
        model.addColumn("Alamat. ");
        model.addColumn("Tanggal Lahir. ");
        model.addColumn("Jenis Kelamin. ");
        model.addColumn("Jabatan. ");
        try{
            int no = 1;
            Connection TugasVisual = DriverManager.getConnection("jdbc:mysql://localhost/koperasi","root","");
            ResultSet rs = TugasVisual.createStatement().executeQuery("select * from anggota where kode_agt like '%" + txtcari2.getText() + "%'" +
                "or nama_agt like '%" + txtcari2.getText() + "%'" + "or alamat_agt like '%" + txtcari2.getText() + "%'" );
            while (rs.next()) {
                model.addRow(new Object[]{no++,
                    rs.getString(1),
                    rs.getString(2),
                    rs.getString(3),
                    rs.getString(4),
                    rs.getString(5),
                    rs.getString(6),
                });

            }
            tabelanggota.setModel(model);
            kosongkan_form();
        }catch (Exception e){

        }
    }//GEN-LAST:event_btncari2ActionPerformed

    private void cbdivisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbdivisiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbdivisiActionPerformed

    private void cbstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbstatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbstatusActionPerformed

    private void cbagamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbagamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbagamaActionPerformed

    private void txtnama2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnama2ActionPerformed
        txtalamat2.grabFocus();
    }//GEN-LAST:event_txtnama2ActionPerformed

    private void txtalamat2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtalamat2ActionPerformed
        txttlp.grabFocus();
    }//GEN-LAST:event_txtalamat2ActionPerformed

    private void txttlpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttlpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttlpActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncari2;
    private javax.swing.JButton btnedit2;
    private javax.swing.JButton btnhapus2;
    private javax.swing.JButton btnsimpan2;
    private javax.swing.JComboBox<String> cbagama;
    private javax.swing.JComboBox<String> cbdivisi;
    private javax.swing.JComboBox<String> cbjabatan2;
    private javax.swing.JComboBox<String> cbkelamin2;
    private javax.swing.JComboBox<String> cbstatus;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable tabelanggota;
    private javax.swing.JTextField txtalamat2;
    private javax.swing.JTextField txtcari2;
    private javax.swing.JTextField txtkode2;
    private javax.swing.JTextField txtnama2;
    private com.toedter.calendar.JDateChooser txttanggal2;
    private javax.swing.JTextField txttlp;
    // End of variables declaration//GEN-END:variables
}
