/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form_main;

import com.sun.glass.events.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Asus
 */
public class Tunai extends javax.swing.JPanel {
    
    ResultSet rsbarang=null;
    ResultSet rsanggota=null;
    
    public void setTanggal(){
      java.util.Date tgl = new java.util.Date();
        SimpleDateFormat format = new SimpleDateFormat("dd - MM - yyyy");
        tanggal.setText(format.format(tgl));
    }
    
    public void otomatis(){
        
        try{
            Connection conn = (Connection)koneksi.configDB();
            Statement stt = conn.createStatement();
            ResultSet rs = stt.executeQuery("Select Max(Right(kode_bayar,4)) as no from tunai");
            
            
            while (rs.next()) {
                if (rs.first() == false) {
                    txtkode_bayar.setText("KBT-0001");
                } else {
                    rs.last();
                    int auto_id = rs.getInt(1) + 1;
                    String no = String.valueOf(auto_id);
                    int NomorJual = no.length();
                    //MENGATUR jumlah 0
                    for (int j = 0; j < 4 - NomorJual; j++) {
                        no = "0" + no;
                    }
                    txtkode_bayar.setText("KBT-" + no);
                }
            }
            rs.close();
            stt.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "ERROR: \n" + e.toString(),
                    "Kesalahan", JOptionPane.WARNING_MESSAGE);
        }
    }
    
NumberFormat nf = NumberFormat.getNumberInstance(new Locale("in","ID"));
    
    private void jmlTotalHarga() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    int sub_total = 0;
    for(int a = 0; a< keranjang.getRowCount(); a ++){
        sub_total += Integer.parseInt((String) keranjang.getValueAt(a, 6).toString().replace(".", ""));
    }
    
    lbltotal.setText(nf.format(sub_total));

    }
    
   
    private void bersih_anggota(){
        txtkode_anggota.setText("");
        txtnama.setText("");
        txtdivisi.setText("");
        txtjabatan.setText("");
    }
    private void bersih_barang(){
        
        txtkode_barang.setText("");
        txtjenis.setText("");
        txtmerek.setText("");
        txtharga.setText("");
        txtqty.setText("");
    }
    private void bersih_pembayaran(){
        lbltotal.setText("");
        lblkembalian.setText("");
        txtbunga.setText("");
        txtbayar.setText("");
        txthasil_diskon.setText("");
        txtdiskon.setText("0");
        
    }
    
    public void kosong_tabel(){
        DefaultTableModel model = (DefaultTableModel) keranjang.getModel();
        
        while (model.getRowCount()>0) {
            model.removeRow(0);
        }
    }

    /**
     * Creates new form Tunai
     */
    public Tunai() {
        initComponents();
        otomatis();
        kosong_tabel();
        bersih_anggota();
        bersih_barang();
        setTanggal();
        
        btnbayar.setEnabled(false);
        btncetak.setEnabled(false);
        btndiskon.setEnabled(false);
        txtdiskon.setEnabled(false);
        txthasil_diskon.setEnabled(false);
        
        diskon = 0;
        txtdiskon.setText(String.valueOf(diskon));
    }

    private int qty, kode,jenis,merek,harga,total,bunga,diskon,hasil;
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel19 = new javax.swing.JLabel();
        jLabel63 = new javax.swing.JLabel();
        txtkode_bayar = new javax.swing.JTextField();
        jLabel62 = new javax.swing.JLabel();
        tanggal = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel61 = new javax.swing.JLabel();
        txtkode_anggota = new javax.swing.JTextField();
        txtnama = new javax.swing.JTextField();
        jLabel66 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        txtdivisi = new javax.swing.JTextField();
        txtjabatan = new javax.swing.JTextField();
        jLabel71 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel65 = new javax.swing.JLabel();
        txtkode_barang = new javax.swing.JTextField();
        txtjenis = new javax.swing.JTextField();
        jLabel64 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        txtharga = new javax.swing.JTextField();
        txtmerek = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel72 = new javax.swing.JLabel();
        txtqty = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        keranjang = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        txtbayar = new javax.swing.JTextField();
        jLabel74 = new javax.swing.JLabel();
        lblkembalian = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        btndiskon = new javax.swing.JButton();
        txtdiskon = new javax.swing.JTextField();
        jLabel76 = new javax.swing.JLabel();
        txthasil_diskon = new javax.swing.JTextField();
        lbltotal = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btnbayar = new javax.swing.JButton();
        btncetak = new javax.swing.JButton();
        jLabel77 = new javax.swing.JLabel();
        txtbunga = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 255, 204));

        jLabel19.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel19.setText("BAYAR TUNAI");

        jLabel63.setText("Kode Bayar");

        txtkode_bayar.setEditable(false);
        txtkode_bayar.setBackground(new java.awt.Color(204, 255, 204));

        jLabel62.setText("Tgl Pembayaran  :");

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jLabel61.setText("Kode Anggota");

        txtkode_anggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkode_anggotaActionPerformed(evt);
            }
        });
        txtkode_anggota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtkode_anggotaKeyPressed(evt);
            }
        });

        txtnama.setEditable(false);
        txtnama.setBackground(new java.awt.Color(204, 204, 204));

        jLabel66.setText("Nama");

        jLabel70.setText("Divisi");

        txtdivisi.setEditable(false);
        txtdivisi.setBackground(new java.awt.Color(204, 204, 204));

        txtjabatan.setEditable(false);
        txtjabatan.setBackground(new java.awt.Color(204, 204, 204));
        txtjabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjabatanActionPerformed(evt);
            }
        });

        jLabel71.setText("Jabatan");

        jLabel21.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel21.setText("DATA ANGGOTA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel61)
                                    .addGap(18, 18, 18))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel66)
                                        .addComponent(jLabel70))
                                    .addGap(59, 59, 59)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel71)
                                .addGap(47, 47, 47)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtjabatan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtdivisi, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtnama, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtkode_anggota, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel61)
                    .addComponent(txtkode_anggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel66)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel70)
                    .addComponent(txtdivisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel71)
                    .addComponent(txtjabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jLabel65.setText("Kode Barang");

        txtkode_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkode_barangActionPerformed(evt);
            }
        });
        txtkode_barang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtkode_barangKeyPressed(evt);
            }
        });

        txtjenis.setEditable(false);
        txtjenis.setBackground(new java.awt.Color(204, 204, 204));

        jLabel64.setText("Jenis Barang");

        jLabel68.setText("Merek");

        jLabel69.setText("Harga");

        txtharga.setEditable(false);
        txtharga.setBackground(new java.awt.Color(204, 204, 204));

        txtmerek.setEditable(false);
        txtmerek.setBackground(new java.awt.Color(204, 204, 204));

        jLabel20.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel20.setText("DATA BARANG");

        jLabel72.setText("Jumlah Barang");

        jButton1.setText("Tambah Ke Keranjang");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel68)
                                .addComponent(jLabel64)
                                .addComponent(jLabel69)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel65)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtkode_barang, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtjenis, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtmerek, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jLabel20))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel72)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtqty, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtkode_barang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel65))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel64)
                    .addComponent(txtjenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel68)
                    .addComponent(txtmerek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel69)
                    .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtqty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel72))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        keranjang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Kode Barang", "Jenis", "Merek", "Harga", "Qty", "Total"
            }
        ));
        jScrollPane1.setViewportView(keranjang);

        jLabel22.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel22.setText("KERANJANG");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 676, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel22)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jLabel23.setFont(new java.awt.Font("Tw Cen MT", 1, 14)); // NOI18N
        jLabel23.setText("PEMBAYARAN");

        jLabel73.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel73.setText("Total Pembayaran");

        jLabel67.setText("Uang Pembayaran");

        txtbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbayarActionPerformed(evt);
            }
        });

        jLabel74.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel74.setText("Kembalian");

        lblkembalian.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblkembalian.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel75.setText("Diskon ");

        btndiskon.setText("Tambahkan Diskon");
        btndiskon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndiskonActionPerformed(evt);
            }
        });

        txtdiskon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdiskonActionPerformed(evt);
            }
        });

        jLabel76.setText("%     RP.");

        lbltotal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbltotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnbayar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnbayar.setText("BAYAR");
        btnbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbayarActionPerformed(evt);
            }
        });

        btncetak.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btncetak.setText("CETAK");
        btncetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncetakActionPerformed(evt);
            }
        });

        jLabel77.setText("Bunga");

        txtbunga.setEditable(false);
        txtbunga.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbltotal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                    .addGap(47, 47, 47)
                                    .addComponent(jLabel73)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btnbayar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btncetak))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel67)
                                    .addComponent(jLabel77))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtbunga, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtbayar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btndiskon, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(jLabel75)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblkembalian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(txtdiskon, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel76)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txthasil_diskon, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel74)
                                .addGap(149, 149, 149)))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btndiskon)
                        .addGap(21, 21, 21)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel75)
                            .addComponent(txtdiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel76)
                            .addComponent(txthasil_diskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel74))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel73)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbltotal, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblkembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel77)
                            .addComponent(txtbunga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel67)
                            .addComponent(txtbayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnbayar)
                        .addComponent(btncetak))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel63)
                        .addGap(10, 10, 10)
                        .addComponent(txtkode_bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel62)
                        .addGap(10, 10, 10)
                        .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtkode_bayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel63)
                            .addComponent(jLabel62))))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(521, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtjabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjabatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjabatanActionPerformed

    private void btnbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbayarActionPerformed
      int bayar;
      bayar = Integer.parseInt(txtbayar.getText());
        btncetak.setEnabled(true);
        
        try {
            int baris = keranjang.getRowCount();
            
            for (int i = 0; i < baris; i++) {
                String sql = "INSERT INTO tunai(kode_bayar, tanggal_bayar, kode_agt, nama_agt"
                        + ",divisi_agt, jabatan_agt, kode_brg, jenis_brg, merek_brg, harga_brg"
                        + ", jumlah_unit, total_harga, total_bayar, diskon, hasil_diskon, bunga"
                        + ", pembayaran, kembalian) VALUES('"
                        + txtkode_bayar.getText() +"','"+ tanggal.getText() +"','"+ txtkode_anggota.getText() +"','"+ txtnama.getText() +"','"
                        + txtdivisi.getText() +"','"+ txtjabatan.getText() +"','"+ keranjang.getValueAt(i, 1) +"','"+ keranjang.getValueAt(i, 2) +"','"
                        + keranjang.getValueAt(i, 3) +"','"+ keranjang.getValueAt(i, 4) +"','"+ keranjang.getValueAt(i, 5) +"','"+ keranjang.getValueAt(i, 6) +"','"
                        + lbltotal.getText()+"','"+ txtdiskon.getText() +"','"+ txthasil_diskon.getText()+"','"+ txtbunga.getText() +"','"+ nf.format(bayar) +"','"+ lblkembalian.getText() + "')" ;
                java.sql.Connection conn = (Connection)koneksi.configDB();
                java.sql.PreparedStatement pstm = conn.prepareStatement(sql);
                pstm.execute();
            
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        JOptionPane.showMessageDialog(null, "Pembayaran Berhasil...");
           bersih_barang();
           bersih_pembayaran();       
           setTanggal();
    }//GEN-LAST:event_btnbayarActionPerformed

    private void btncetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncetakActionPerformed
         try{
                String path="src/report/Kwitansi_Tunai.jasper";
                HashMap parameter = new HashMap();
                java.sql.Connection conn = (Connection)koneksi.configDB();
                parameter.put("kode", txtkode_bayar.getText());
                JasperPrint print = JasperFillManager.fillReport(path, parameter, conn);
                JasperViewer.viewReport(print, false);
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
         otomatis();
         bersih_anggota();
         bersih_pembayaran();
         kosong_tabel();
         setTanggal();
    }//GEN-LAST:event_btncetakActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        qty = Integer.parseInt(txtqty.getText());
        harga = Integer.parseInt(txtharga.getText().replace(".", ""));
        total = qty * harga;
        
       if(txtqty.getText().equals("")){
           return;
           
       }else{
           DefaultTableModel model = (DefaultTableModel) keranjang.getModel();
           
           Object obj [] = new Object[7];
           obj [1] = txtkode_barang.getText();
           obj [2] = txtjenis.getText();
           obj [3] = txtmerek.getText();
           obj [4] = txtharga.getText();
           obj [5] = qty;
           obj [6] = nf.format(total);
           
           model.addRow(obj);
           
           int baris = model.getRowCount();
           
           for(int a = 0; a < baris; a ++){
               String no = String.valueOf(a + 1);
               model.setValueAt(no + ".", a, 0);
           }
            keranjang.setRowHeight(30);
       }
       jmlTotalHarga();
       bersih_barang();
       btndiskon.setEnabled(true);
       
       total = Integer.parseInt(lbltotal.getText().replace(".", ""));
       bunga = total * 10/100;
       txtbunga.setText(nf.format(bunga));
       
       harga =total + bunga;
       lbltotal.setText(nf.format(harga));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tampil_anggota(String key) {try{
   // Statement stt=Connection.createStatement();
        Connection conn=(Connection)koneksi.configDB();
        Statement stt=conn.createStatement();
        rsanggota=stt.executeQuery("SELECT * from anggota WHERE kode_agt LIKE '%"+key+"%'");  
        if(rsanggota.next()){
              
        
        String nama = rsanggota.getString("nama_agt");
        txtnama.setText(nama);
        
        String divisi = rsanggota.getString("divisi");
        txtdivisi.setText(divisi);
        
        String jabatan = rsanggota.getString("jabatan_agt");
        txtjabatan.setText(jabatan);
        
            }
            else{
                JOptionPane.showMessageDialog(null, "Data Tidak Ada");
            }
    }catch (Exception ex) {
        System.err.println(ex.getMessage());
        }
    }
    
    private void txtkode_anggotaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtkode_anggotaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            String key=txtkode_anggota.getText();
            System.out.println(key);

            if(key!=""){
                tampil_anggota(key);
            }else{
                JOptionPane.showMessageDialog(null, "Data Tidak Ada");
            }
        }
    }//GEN-LAST:event_txtkode_anggotaKeyPressed

    private void tampil_barang(String key) {try{
   // Statement stt=Connection.createStatement();
        Connection conn=(Connection)koneksi.configDB();
        Statement stt=conn.createStatement();
        rsbarang=stt.executeQuery("SELECT * from barang WHERE kode_brg LIKE '%"+key+"%'");  
        if(rsbarang.next()){
              
        
        String jenis = rsbarang.getString("jenis_brg");
        txtjenis.setText(jenis);
        
        String merek = rsbarang.getString("nama");
        txtmerek.setText(merek);
        
        Integer harga = rsbarang.getInt("harga");
        txtharga.setText(nf.format(harga));
        
            }
            else{
                JOptionPane.showMessageDialog(null, "Data Tidak Ada");
            }
    }catch (Exception ex) {
        System.err.println(ex.getMessage());
        }
    }
    
    private void txtkode_barangKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtkode_barangKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

            String key=txtkode_barang.getText();
            System.out.println(key);

            if(key!=""){
                tampil_barang(key);
            }else{
                JOptionPane.showMessageDialog(null, "Data Tidak Ada");
            }
        }
       
    }//GEN-LAST:event_txtkode_barangKeyPressed

    private void txtkode_anggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkode_anggotaActionPerformed
        txtkode_barang.grabFocus();
    }//GEN-LAST:event_txtkode_anggotaActionPerformed

    private void txtkode_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkode_barangActionPerformed
        txtqty.grabFocus();
    }//GEN-LAST:event_txtkode_barangActionPerformed

    private void btndiskonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndiskonActionPerformed
        txtdiskon.setEnabled(true);
        txthasil_diskon.setEnabled(true);
        txtdiskon.setText("");
    }//GEN-LAST:event_btndiskonActionPerformed

    private void txtdiskonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdiskonActionPerformed
        total = Integer.parseInt(lbltotal.getText().replace(".", ""));
        diskon = Integer.parseInt(txtdiskon.getText());
        harga = total * diskon/100;
        txthasil_diskon.setText(nf.format(harga));
        
        hasil = total - harga;
        lbltotal.setText(nf.format(hasil));
    }//GEN-LAST:event_txtdiskonActionPerformed

    private void txtbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbayarActionPerformed
                int bayar, tagihan;
                tagihan = Integer.parseInt(lbltotal.getText().replace(".", ""));
                bayar = Integer.parseInt(txtbayar.getText());
               
                int totalKembalian ;
                
                if(bayar > tagihan){
                    
                    totalKembalian = bayar - tagihan;
                    btnbayar.setEnabled(true);
                    lblkembalian.setText(nf.format(totalKembalian));
                    
                }else{
                    JOptionPane.showMessageDialog(null, "Uang Pembayaran Kurang !!!");
                }
                
                   }//GEN-LAST:event_txtbayarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbayar;
    private javax.swing.JButton btncetak;
    private javax.swing.JButton btndiskon;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable keranjang;
    private javax.swing.JLabel lblkembalian;
    private javax.swing.JLabel lbltotal;
    private javax.swing.JLabel tanggal;
    private javax.swing.JTextField txtbayar;
    private javax.swing.JTextField txtbunga;
    private javax.swing.JTextField txtdiskon;
    private javax.swing.JTextField txtdivisi;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txthasil_diskon;
    private javax.swing.JTextField txtjabatan;
    private javax.swing.JTextField txtjenis;
    private javax.swing.JTextField txtkode_anggota;
    private javax.swing.JTextField txtkode_barang;
    private javax.swing.JTextField txtkode_bayar;
    private javax.swing.JTextField txtmerek;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtqty;
    // End of variables declaration//GEN-END:variables
}
