/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form_user;

import form_main.koneksi;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class data_anggota extends javax.swing.JPanel {

    /**
     * Creates new form data_anggota
     */
    public data_anggota() {
        initComponents();
        tampil_anggota();
        txtcari2.grabFocus();
    }

    private void cari (){
        DefaultTableModel model = new DefaultTableModel();
           model.addColumn("No. ");
           model.addColumn("Kode. ");
           model.addColumn("Nama. ");
           model.addColumn("Alamat. ");
           model.addColumn("No.Tlp. ");
           model.addColumn("Tanggal Lahir. ");
           model.addColumn("Status. ");
           model.addColumn("Jenis Kelamin. ");
           model.addColumn("Jabatan. ");
           model.addColumn("Divisi. ");
           model.addColumn("Agama. ");
        try{
            int no = 1;
            Connection TugasVisual = DriverManager.getConnection("jdbc:mysql://localhost/koperasi","root","");
            ResultSet res = TugasVisual.createStatement().executeQuery("select * from anggota where kode_agt like '%" + txtcari2.getText() + "%'" +
                "or nama_agt like '%" + txtcari2.getText() + "%'" + "or alamat_agt like '%" + txtcari2.getText() + "%'" );
            while (res.next()) {
             model.addRow(new Object[]{no++,
                 res.getString(1),
                 res.getString(2),
                 res.getString(3),
                 res.getString(4),
                 res.getString(5),
                 res.getString(6),
                 res.getString(7),
                 res.getString(8),
                 res.getString(9),
                 res.getString(10) 

                });

            }
            tabelanggota.setModel(model);
       
        }catch (Exception e){

        }
    }
    
    private void tampil_anggota(){
          
           DefaultTableModel model = new DefaultTableModel();
           model.addColumn("No. ");
           model.addColumn("Kode. ");
           model.addColumn("Nama. ");
           model.addColumn("Alamat. ");
           model.addColumn("No.Tlp. ");
           model.addColumn("Tanggal Lahir. ");
           model.addColumn("Status. ");
           model.addColumn("Jenis Kelamin. ");
           model.addColumn("Jabatan. ");
           model.addColumn("Divisi. ");
           model.addColumn("Agama. ");
          
           
           try{
            int no = 1;
            String sql = "SELECT * FROM anggota";
            java.sql.Connection conn = (Connection)koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            while(res.next()){
                model.addRow(new Object[]{no++,res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6),res.getString(7),res.getString(8),res.getString(9),res.getString(10)}); 
            
                tabelanggota.setModel(model);
            }
           
           }catch (SQLException e){
               System.out.println("Error :"+ e.getMessage());
           }
       } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelanggota = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtcari2 = new javax.swing.JTextField();
        btncari2 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(204, 255, 204));
        kGradientPanel1.setkStartColor(new java.awt.Color(255, 255, 204));

        tabelanggota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelanggota);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("DAFTAR ANGGOTA KOPERASI DUTA USAHA");

        txtcari2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcari2ActionPerformed(evt);
            }
        });

        btncari2.setText("Cari");
        btncari2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncari2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(txtcari2, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btncari2))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(276, 276, 276)
                        .addComponent(jLabel1)))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncari2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcari2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                .addGap(49, 49, 49))
        );

        add(kGradientPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void txtcari2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcari2ActionPerformed
         cari();
    }//GEN-LAST:event_txtcari2ActionPerformed

    private void btncari2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncari2ActionPerformed
         cari();
    }//GEN-LAST:event_btncari2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncari2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JTable tabelanggota;
    private javax.swing.JTextField txtcari2;
    // End of variables declaration//GEN-END:variables
}
