/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form_user;

import form_main.koneksi;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class data_kredit extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public data_kredit() {
        initComponents();
        tampil_kredit();
    }

    private void tampil_kredit(){
          
           DefaultTableModel model = new DefaultTableModel();
           model.addColumn("No. ");
           model.addColumn("Kode Bayar. ");
           model.addColumn("Tanggal. ");
           model.addColumn("Kode Kredit. ");
           model.addColumn("Lama Cicil. ");
           model.addColumn("Bayar. ");
           model.addColumn("Sisa. ");
           model.addColumn("Keterangan. ");
           model.addColumn("Angsuran. ");
           
           try{
            int no = 1;
            String sql = "SELECT * FROM kredit";
            java.sql.Connection conn = (Connection)koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            while(res.next()){
                model.addRow(new Object[]{no++,res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6),res.getString(7),res.getString(8)}); 
            
            tabelkredit.setModel(model); 
            }
                
           }catch (SQLException e){
               System.out.println("Error :"+ e.getMessage());
           }
       }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelkredit = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtcari2 = new javax.swing.JTextField();
        txtcari3 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        kGradientPanel1.setkEndColor(new java.awt.Color(204, 255, 204));
        kGradientPanel1.setkStartColor(new java.awt.Color(255, 255, 204));

        tabelkredit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelkredit);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("DAFTAR PEMBAYARAN KREDIT PADA KOPERASI DUTA USAHA");

        txtcari2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcari2ActionPerformed(evt);
            }
        });

        txtcari3.setText("Cari");
        txtcari3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcari3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(txtcari2, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtcari3))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jLabel1)))
                .addContainerGap(226, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcari3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcari2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                .addGap(49, 49, 49))
        );

        add(kGradientPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void txtcari2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcari2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcari2ActionPerformed

    private void txtcari3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcari3ActionPerformed
        
        DefaultTableModel model = new DefaultTableModel();
           model.addColumn("No. ");
           model.addColumn("Kode Bayar. ");
           model.addColumn("Tanggal. ");
           model.addColumn("Kode Kredit. ");
           model.addColumn("Lama Cicil. ");
           model.addColumn("Bayar. ");
           model.addColumn("Sisa. ");
           model.addColumn("Keterangan. ");
           model.addColumn("Angsuran. ");
           
        try{
            int no = 1;
            Connection TugasVisual = DriverManager.getConnection("jdbc:mysql://localhost/koperasi","root","");
            ResultSet rss = TugasVisual.createStatement().executeQuery("select * from kredit where kode_bayar like '%" + txtcari3.getText() + "%'" +
                "or kode_kredit like '%" + txtcari3.getText() + "%'" + "or tanggal_bayar like '%" + txtcari3.getText() + "%'" );
            while (rss.next()) {
                model.addRow(new Object[]{no++,
                    rss.getString(1),
                    rss.getString(2),
                    rss.getString(3),
                    rss.getString(4),
                    rss.getString(5),
                    rss.getString(6),
                    rss.getString(7),
                    rss.getString(8),
                });
            }
            tabelkredit.setModel(model);
        }catch (Exception e){

        }
    }//GEN-LAST:event_txtcari3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JTable tabelkredit;
    private javax.swing.JTextField txtcari2;
    private javax.swing.JButton txtcari3;
    // End of variables declaration//GEN-END:variables
}
